<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>DeltaText</AssemblyName>
    <RootNamespace>Delta.Text</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tests/**/*.cs" />
    <Compile Remove="**/obj/**/*.cs" />
    <Compile Remove="**/bin/**/*.cs" />
    <None Remove="Tests/**/*.ttf" />
    <None Remove="Tests/OFL.txt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DeltaMaths\DeltaMaths.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.Fonts" Version="3.0.0" />
  </ItemGroup>
</Project>
