<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>DeltaText</AssemblyName>
    <RootNamespace>Delta.Text</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <SixLaborsFontsPackageVersion Condition="'$(SixLaborsFontsPackageVersion)' == ''">3.1.0-fork.cadda774</SixLaborsFontsPackageVersion>
    <SixLaborsFontsPackageSource Condition="'$(SixLaborsFontsPackageSource)' == ''">$(MSBuildProjectDirectory)/../../../Furnace/Packages/SixLabors.Fonts-Fork</SixLaborsFontsPackageSource>
    <RestoreSources>$(SixLaborsFontsPackageSource);$(RestoreSources)</RestoreSources>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../DeltaMaths/src/DeltaMaths/DeltaMaths.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.Fonts" Version="$(SixLaborsFontsPackageVersion)" />
  </ItemGroup>
</Project>
