<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>DeltaText</AssemblyName>
    <RootNamespace>Delta.Text</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../DeltaMaths/src/DeltaMaths/DeltaMaths.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.Fonts" Version="3.1.0" />
  </ItemGroup>
</Project>
